/**
 * PDF Export Utility for Lecture Me
 * Copyright (c) 2026 Charles Kendrick. All Rights Reserved.
 */

import { jsPDF } from 'jspdf';

interface StudyGuidePDFData {
  title: string;
  courseName?: string;
  date: Date;
  transcription: string;
  summary: string;
  keyPoints: string;
}

interface QAPDFData {
  title: string;
  courseName?: string;
  date: Date;
  questions: Array<{
    question: string;
    answer: string;
    createdAt: Date;
  }>;
}

interface FlashcardsPDFData {
  courseName?: string;
  date: Date;
  flashcards: Array<{
    front: string;
    back: string;
  }>;
}

const PURPLE_PRIMARY: [number, number, number] = [124, 58, 237]; // #7C3AED
const PURPLE_LIGHT: [number, number, number] = [196, 181, 253]; // #C4B5FD
const GRAY_TEXT: [number, number, number] = [55, 65, 81]; // #374151

export function generateStudyGuidePDF(data: StudyGuidePDFData): Buffer {
  const doc = new jsPDF();
  let yPosition = 20;

  // Header with branding
  doc.setFillColor(...PURPLE_PRIMARY);
  doc.rect(0, 0, 210, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Lecture Me', 105, 15, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('College Edition - Study Guide', 105, 22, { align: 'center' });

  yPosition = 40;

  // Title
  doc.setTextColor(...GRAY_TEXT);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, 20, yPosition);
  yPosition += 10;

  // Course and date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (data.courseName) {
    doc.text(`Course: ${data.courseName}`, 20, yPosition);
    yPosition += 6;
  }
  doc.text(`Generated: ${data.date.toLocaleDateString()}`, 20, yPosition);
  yPosition += 15;

  // Summary section
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PURPLE_PRIMARY);
  doc.text('Summary', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY_TEXT);
  const summaryLines = doc.splitTextToSize(data.summary, 170);
  doc.text(summaryLines, 20, yPosition);
  yPosition += summaryLines.length * 5 + 10;

  // Key Points section
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PURPLE_PRIMARY);
  doc.text('Key Points', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY_TEXT);
  
  const keyPointsArray = data.keyPoints.split('|');
  keyPointsArray.forEach((point, index) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    doc.text(`${index + 1}. ${point.trim()}`, 25, yPosition);
    yPosition += 7;
  });

  yPosition += 10;

  // Full Transcription section
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PURPLE_PRIMARY);
  doc.text('Full Transcription', 20, yPosition);
  yPosition += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY_TEXT);
  const transcriptionLines = doc.splitTextToSize(data.transcription, 170);
  
  transcriptionLines.forEach((line: string) => {
    if (yPosition > 280) {
      doc.addPage();
      yPosition = 20;
    }
    doc.text(line, 20, yPosition);
    yPosition += 5;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text('Generated by Lecture Me - lectureme.app', 105, 295, { align: 'center' });
  }

  return Buffer.from(doc.output('arraybuffer'));
}

export function generateQAPDF(data: QAPDFData): Buffer {
  const doc = new jsPDF();
  let yPosition = 20;

  // Header with branding
  doc.setFillColor(...PURPLE_PRIMARY);
  doc.rect(0, 0, 210, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Lecture Me', 105, 15, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('College Edition - Q&A Session', 105, 22, { align: 'center' });

  yPosition = 40;

  // Title
  doc.setTextColor(...GRAY_TEXT);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(data.title, 20, yPosition);
  yPosition += 10;

  // Course and date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (data.courseName) {
    doc.text(`Course: ${data.courseName}`, 20, yPosition);
    yPosition += 6;
  }
  doc.text(`Generated: ${data.date.toLocaleDateString()}`, 20, yPosition);
  doc.text(`${data.questions.length} Questions`, 150, yPosition);
  yPosition += 15;

  // Q&A pairs
  data.questions.forEach((qa, index) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    // Question
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PURPLE_PRIMARY);
    doc.text(`Q${index + 1}:`, 20, yPosition);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GRAY_TEXT);
    const questionLines = doc.splitTextToSize(qa.question, 160);
    doc.text(questionLines, 30, yPosition);
    yPosition += questionLines.length * 6 + 5;

    // Answer
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PURPLE_LIGHT);
    doc.text('A:', 20, yPosition);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GRAY_TEXT);
    const answerLines = doc.splitTextToSize(qa.answer, 160);
    doc.text(answerLines, 30, yPosition);
    yPosition += answerLines.length * 5 + 12;

    // Separator line
    if (index < data.questions.length - 1) {
      doc.setDrawColor(...PURPLE_LIGHT);
      doc.line(20, yPosition - 5, 190, yPosition - 5);
    }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text('Generated by Lecture Me - lectureme.app', 105, 295, { align: 'center' });
  }

  return Buffer.from(doc.output('arraybuffer'));
}

export function generateFlashcardsPDF(data: FlashcardsPDFData): Buffer {
  const doc = new jsPDF();
  let yPosition = 20;

  // Header with branding
  doc.setFillColor(...PURPLE_PRIMARY);
  doc.rect(0, 0, 210, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Lecture Me', 105, 15, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('College Edition - Flashcards', 105, 22, { align: 'center' });

  yPosition = 40;

  // Title
  doc.setTextColor(...GRAY_TEXT);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Flashcard Set', 20, yPosition);
  yPosition += 10;

  // Course and date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  if (data.courseName) {
    doc.text(`Course: ${data.courseName}`, 20, yPosition);
    yPosition += 6;
  }
  doc.text(`Generated: ${data.date.toLocaleDateString()}`, 20, yPosition);
  doc.text(`${data.flashcards.length} Cards`, 150, yPosition);
  yPosition += 15;

  // Flashcards
  data.flashcards.forEach((card, index) => {
    if (yPosition > 240) {
      doc.addPage();
      yPosition = 20;
    }

    // Card number and front
    doc.setFillColor(...PURPLE_LIGHT);
    doc.roundedRect(15, yPosition - 5, 180, 35, 3, 3, 'F');
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PURPLE_PRIMARY);
    doc.text(`Card ${index + 1}`, 20, yPosition);
    yPosition += 7;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...GRAY_TEXT);
    const frontLines = doc.splitTextToSize(card.front, 170);
    doc.text(frontLines, 20, yPosition);
    yPosition += frontLines.length * 5 + 10;

    // Back (answer)
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    const backLines = doc.splitTextToSize(card.back, 170);
    doc.text(backLines, 20, yPosition);
    yPosition += backLines.length * 5 + 15;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
    doc.text('Generated by Lecture Me - lectureme.app', 105, 295, { align: 'center' });
  }

  return Buffer.from(doc.output('arraybuffer'));
}
